import Navbar from './components/Navbar'
import './globals.css'
import { Signika_Negative } from 'next/font/google'

import Footer from './components/Footer'
const signika = Signika_Negative({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-signika'
})

export const metadata = {
  title: 'Bankich | The new bank',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${signika.variable} font-signika relative min-h-screen `}
      >
        <Navbar />
        <div className='pb-60'>{children}</div>
        <Footer />
      </body>
    </html>
  )
}
